### ISSUE TITLE
HI,My friend,I like your works very very much

### ISSUE THREAD

**Issue by duhongfei0535** [MacKentoch/react-redux-bootstrap-webpack-starter#4]
... yes,I like it ,but why is JQ still used?

**Comment by MacKentoch** [comment]
Thank you @duhongfei0535 

jQuery is not that much useful you are right.

I was just a bit lazy [here](https://github.com/MacKentoch/react-redux-bootstrap-webpack-starter/blob/master/src/app/components/backToTop/BackToTop.js#L49)

**Comment by MacKentoch** [comment]
I initially didn't use that much `react-bootstrap` since there were a bug where console was full of errors and warnings (*React breaking change on props: I don't remember which version, I suppose early 15.x*).

So it was really bad so that I used basic bootstrap.

Now (*and since a while*) it is ok using full react-bootstrap.
